package com.model.pojo;
// Generated Sep 30, 2019 6:39:29 PM by Hibernate Tools 4.3.1

import com.dao.UserDAO;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;



@ManagedBean
@SessionScoped
/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String nama;
     private String password;
     private String email;
     private Integer telpon;

    public User() {
    }

    public User(String nama, String password, String email, Integer telpon) {
       this.nama = nama;
       this.password = password;
       this.email = email;
       this.telpon = telpon;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTelpon() {
        return this.telpon;
    }
    
    public void setTelpon(Integer telpon) {
        this.telpon = telpon;
    }

 public String validateLoginAdmin(String nama){
        UserDAO user = new UserDAO();
        boolean validate = user.validateLogin(this);
        if (validate==true) {
            //this.msgLogin = null;
            //cleardata();
            this.nama = nama;
            return "bookingadmin?faces-redirect=true"; 
           
        }else{
            //this.msgLogin = "Username atau password yang anda masukkan salah.";
            return "loginadmin?faces-redirect=true";
        }
    }    


}


